"""Reference helpers for optional T-Trace profiles."""

from .lineage_compaction import (
    LINEAGE_ACCUMULATOR_SCHEMA,
    LINEAGE_COMPACTION_REASON,
    ZERO_SHA256,
    LineageCompactionAgreement,
    advance_lineage_accumulator,
    build_seed_lineage_accumulator,
    validate_active_lineage_tip,
    validate_lineage_accumulator,
    validate_lineage_compaction,
)
from .lineage_membership import (
    LINEAGE_MEMBERSHIP_ANCHOR_SCHEMA,
    LINEAGE_MEMBERSHIP_REASON,
    LINEAGE_MEMBERSHIP_TREE_ALGORITHM,
    LINEAGE_SELECTIVE_DISCLOSURE_SCHEMA,
    LineageMembershipDecision,
    build_lineage_cycle_summary,
    build_lineage_membership_anchor,
    build_selective_lineage_disclosure,
    validate_lineage_membership_anchor,
    verify_selective_lineage_disclosure,
)
from .portable_causality import (
    BranchEvidence,
    CausalValidationError,
    ReconciliationAgreement,
    ReconciliationVote,
    build_branch_tip,
    build_transition_ref,
    canonical_json_bytes,
    digest_json,
    make_state_ref,
    reconcile_two_branches,
    validate_reconciliation_agreement,
    validate_state_ref,
    validate_transition_ref,
)

__all__ = [
    "BranchEvidence",
    "CausalValidationError",
    "LINEAGE_ACCUMULATOR_SCHEMA",
    "LINEAGE_COMPACTION_REASON",
    "LINEAGE_MEMBERSHIP_ANCHOR_SCHEMA",
    "LINEAGE_MEMBERSHIP_REASON",
    "LINEAGE_MEMBERSHIP_TREE_ALGORITHM",
    "LINEAGE_SELECTIVE_DISCLOSURE_SCHEMA",
    "LineageCompactionAgreement",
    "LineageMembershipDecision",
    "ReconciliationAgreement",
    "ReconciliationVote",
    "ZERO_SHA256",
    "advance_lineage_accumulator",
    "build_branch_tip",
    "build_lineage_cycle_summary",
    "build_lineage_membership_anchor",
    "build_seed_lineage_accumulator",
    "build_selective_lineage_disclosure",
    "build_transition_ref",
    "canonical_json_bytes",
    "digest_json",
    "make_state_ref",
    "reconcile_two_branches",
    "validate_active_lineage_tip",
    "validate_lineage_accumulator",
    "validate_lineage_compaction",
    "validate_lineage_membership_anchor",
    "validate_reconciliation_agreement",
    "validate_state_ref",
    "validate_transition_ref",
    "verify_selective_lineage_disclosure",
]
